create table cmte_id_to_geo (
  CMTE_ID VARCHAR2(9) PRIMARY KEY,
  LATITUDE NUMBER NOT NULL,
  LONGITUDE NUMBER NOT NULL
);
create table cand_id_to_geo (
  CAND_ID VARCHAR2(9) PRIMARY KEY,
  LATITUDE NUMBER NOT NULL,
  LONGITUDE NUMBER NOT NULL
);
create table ind_to_geo (
  SUB_ID NUMBER(19) PRIMARY KEY,
  LATITUDE NUMBER NOT NULL,
  LONGITUDE NUMBER NOT NULL
);

quit;

